package scyther;
/* Generated By:JavaCC: Do not edit this line. PS1TokenizerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PS1TokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int WORD = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int PRICE = 9;
  /** RegularExpression Id. */
  int ALPHANUM = 10;
  /** RegularExpression Id. */
  int PHONE = 11;
  /** RegularExpression Id. */
  int EMAIL = 12;
  /** RegularExpression Id. */
  int DOMAIN = 13;
  /** RegularExpression Id. */
  int URL = 14;
  /** RegularExpression Id. */
  int PROTOCOL = 15;
  /** RegularExpression Id. */
  int COMMENT = 16;
  /** RegularExpression Id. */
  int TAG = 17;
  /** RegularExpression Id. */
  int LT = 18;
  /** RegularExpression Id. */
  int GT = 19;
  /** RegularExpression Id. */
  int BANG = 20;
  /** RegularExpression Id. */
  int EQUALS = 21;
  /** RegularExpression Id. */
  int QUOTE = 22;
  /** RegularExpression Id. */
  int LPAR = 23;
  /** RegularExpression Id. */
  int RPAR = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int PERIOD = 26;
  /** RegularExpression Id. */
  int COLON = 27;
  /** RegularExpression Id. */
  int SLASH = 28;
  /** RegularExpression Id. */
  int DASH = 29;
  /** RegularExpression Id. */
  int ATSIGN = 30;
  /** RegularExpression Id. */
  int DOLLAR = 31;
  /** RegularExpression Id. */
  int APOS = 32;
  /** RegularExpression Id. */
  int OTHER = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<WORD>",
    "<NUMBER>",
    "<PRICE>",
    "<ALPHANUM>",
    "<PHONE>",
    "<EMAIL>",
    "<DOMAIN>",
    "<URL>",
    "<PROTOCOL>",
    "<COMMENT>",
    "<TAG>",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"=\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"/\"",
    "\"-\"",
    "\"@\"",
    "\"$\"",
    "\"\\\'\"",
    "<OTHER>",
  };

}
